/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parameters for ensureRepoReady */
export interface EnsureRepoReadyParams {
  repoRoot: string
}
/** Result from ensureRepoReady */
export interface EnsureRepoReadyResult {
  isGitRepo: boolean
  defaultBranch?: string
  remoteUrl?: string
}
/** Parameters for ensureWorktree */
export interface EnsureWorktreeParams {
  repoRoot: string
  branch: string
  worktreeBaseDir: string
  pathTemplate?: string
}
/** Result from ensureWorktree */
export interface EnsureWorktreeResult {
  branch: string
  worktreePath: string
}
/** Worktree information */
export interface WorktreeInfo {
  branch: string
  path: string
  isMain: boolean
  isLocked: boolean
}
/** Parameters for listWorktrees */
export interface ListWorktreesParams {
  repoRoot: string
}
/** Parameters for removeWorktree */
export interface RemoveWorktreeParams {
  repoRoot: string
  branch: string
}
/** Ensure a repository is ready and return basic info */
export declare function ensureRepoReady(params: EnsureRepoReadyParams): Promise<EnsureRepoReadyResult>
/** Ensure a worktree exists for the given branch (idempotent) */
export declare function ensureWorktree(params: EnsureWorktreeParams): Promise<EnsureWorktreeResult>
/** List all worktrees in a repository */
export declare function listWorktrees(params: ListWorktreesParams): Promise<Array<WorktreeInfo>>
/** Remove a worktree by branch name */
export declare function removeWorktree(params: RemoveWorktreeParams): Promise<void>
/** Clone progress information */
export interface CloneProgress {
  phase: string
  current: number
  total: number
  percent: number
}
/** Clone a repository from a URL to a target path */
export declare function cloneRepository(url: string, targetPath: string, progressCallback: (progress: CloneProgress) => void): Promise<string>
